In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
m=np.mean(arr)
m

np.float64(5.0)

In [12]:
maxno=np.max(arr)
print(maxno)

9


In [13]:
minno=np.min(arr)
minno

np.int64(1)

In [14]:
sumno=np.sum(arr)
sumno

np.int64(45)

In [16]:
maxno
minno
sumno

np.int64(45)

In [18]:
arr1=np.array([14,56,78])
arr2=np.array([23,45,67])
print(arr1)
print(arr2)

[14 56 78]
[23 45 67]


In [19]:
print(arr1+arr2)

[ 37 101 145]


In [20]:
print(arr1-arr2)

[-9 11 11]


In [21]:
print(arr1*arr2)

[ 322 2520 5226]


In [22]:
print(arr1/arr2)

[0.60869565 1.24444444 1.1641791 ]


In [23]:
print(arr1%arr2)

[14 11 11]
